owner: removededm
repo: status

sites:
  - name: RemovedEDM
    url: https://removededm.com
    expectedStatusCodes:
    - 200
  - name: RemovedEDM Editors
    url: https://editors.removededm.com
    expectedStatusCodes:
    - 403

status-website:
  cname: status.removededm.com
  logoUrl: https://removededm.com/w/img_auth.php/c/c9/Logo.png
  favicon: https://removededm.com/w/img_auth.php/c/c9/Logo.png
  name: RemovedEDM Status
  navbar:
    - title: Status
      href: /
  css: ".svelte-jbr799 { display:none; }"
